# Default setup is given for MySQL with ruby1.9. If you're running Redmine
# with MySQL and ruby1.8, replace the adapter name with `mysql`.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).


#production:
#  adapter: mysql2
#  database: bitnami_redmine
#  host: 192.168.8.155
#  username: bitnami
#  password: "d58153bda9"
#  encoding: utf8


#production:
#  adapter: mysql2
#  database: bitnami_redmine
#  host: 192.168.8.155
#  port: 3306
#  username: root
#  password: welcome123
#  encoding: utf8


# backup working port

production:
  adapter: mysql2
  database: new_stage
  server: 192.168.4.74
  host: 192.168.4.74
  port: 3306
  username: root
  password: root
  encoding: utf8
development:
  adapter: mysql2
  database: new_stage
  server: 192.168.4.74
  host: 192.168.4.74
  port: 3306
  username: root
  password: root
  encoding: utf8

#production:
#  adapter: mysql2
#  database: bitnami_redmine
##  server: 192.168.16.125
#  host: localhost
##  port: 3306
#  username: root
#  password: root
#  encoding: utf8
#redmine_cr4_test_after_build
#redmine_after_time_build
#
#production:
#  adapter: mysql2
#  database: bitnami_redmine_prod
#  host: 192.168.8.155
##  database: redmine_local_dump_latest2
##  host: 192.168.9.104
#  username: root
#  password: root
#  encoding: utf8

#production:
#  adapter: mysql2
#  database: bitnami_redmine_prod
#  host: 192.168.8.155
#  port: 3306
#  username: root
#  password: welcome123
#  encoding: utf8
#  reconnect: true
#  pool: 33


#development:
#  adapter: mysql2
#  database: redmine_development
#  host: localhost
#  username: root
#  password: root
#  encoding: utf8

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: mysql2
  database: redmine_test
  host: localhost
  username: root
  password: root
  encoding: utf8

# PostgreSQL configuration example
#production:
#  adapter: postgresql
#  database: redmine
#  host: localhost
#  username: postgres
#  password: "postgres"

# SQLite3 configuration example
#production:
#  adapter: sqlite3
#  database: db/redmine.sqlite3

# SQL Server configuration example
#production:
#  adapter: sqlserver
#  database: redmine
#  host: localhost
#  username: jenkins
#  password: jenkins
